services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "3e1c6b17687a29a21bfe9d53e2c5e9ac423744fb69535b5a4874184a76010dde"
  tools:
    options:
      jupyter:
        image: ghcr.io/fairmat-nfdi/nomad-distro-template/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "http://mti-thinfilmoasis.uibk.ac.at/api"
  maintainer_email: "nikolai.kraus@uibk.ac.at"

logstash:
  enabled: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
